### ISSUE TITLE
Problems with Mail Merge add-on with Thunderbird 102.12.0 (64-bit)

### ISSUE THREAD

**Issue by Pava1955** [siefkenj/MailMergeP#40]
I tried to use the addon to send email to a list of a *.csv file-
If I insert the {{email}} parameter in the destination I get a red element (as in the figure) and if I send the email it asks me to insert a recipient.
Using the parameters in the body of the emails instead works fine.
_of course I used the column headers_
Can you help me ?
Thank you
![Immagine](https://github.com/siefkenj/MailMerge/assets/135723308/8b8501c2-03cb-48a9-afec-260d8c4bd9b3)

**Comment by siefkenj** [comment]
What version of TB are you using? Did you press Enter in the email field after putting in `{{email}}`?

**Comment by Pava1955** [comment]
Hello and thanks for the reply.
The version of TB I'm using is 102.12.0 (64 bit).
I typed the tab after entering {{email}} and the result is what you see in the image (red color).
Thanks for whatever you can suggest.

**Comment by vladae36** [comment]
I have the same problem  - Tags wont be substituted in the TO: section of the mail - thx a lot

**Comment by siefkenj** [comment]
I have just updated the extension to v2.5.2 which works with TB115+. Could you please check it there?

**Comment by Pava1955** [comment]
Hello and thanks for the new version.
I have a problem ! I didn't understand how to add this extension to Thunderbird (115.5.0 (64 bit))!
Can you give me some help?
Thank you

**Comment by siefkenj** [comment]
You should be able to install it from https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge-p/

**Comment by Pava1955** [comment]
thanks !!

**Comment by siefkenj** [comment]
I assume this issue is resolved?

**Comment by Pava1955** [comment]
Yess thanks !
