### ISSUE TITLE
Cannot merge *.csv with TB 115.6.1 (64 bit)

### ISSUE THREAD

**Issue by 19hope44** [siefkenj/MailMergeP#52]
I have been using MS Outllook mail merge successfully for some years (combined with Access & Word), and before that used ACT! where mail merge was a built-in feature. So I am no stranger to the process. I switched to TB last summer (2023) out of frustration with MS. So far so good apart from all-too-frequent unexplained crashes, EXCEPT mail merge. I tried using the regular version, which totally flummoxed me, and so am trying yours, which I downloaded yesterday. 
The *csv files open successfully, and I enter the field names for Contact and Email correctly (or so I think - they are as the*csv file). Press hard return. I have tried variations on the email address of <{{..@...}}> & {{...@...}}, but no result.
I enter field names in the body of the email, again per the *.csv file. Press hard return
Yesterday, the Preview picked up the field names in the body of the email correctly, but nothing appeared in for the recipients. I gave up, and tried again today from scratch.
Today, NOTHING appears in Preview!
![image](https://github.com/siefkenj/MailMergeP/assets/155631295/4e6c0031-4f8c-477f-8e26-e0c9c042d0af)
![image](https://github.com/siefkenj/MailMergeP/assets/155631295/6fc56e8a-57db-44ef-aee4-9dbedc6abb20)
Any resolution of this gratefully received.

**Comment by 19hope44** [comment]
Sorry, pasted wrong second image. Should be
![image](https://github.com/siefkenj/MailMergeP/assets/155631295/7e41a383-5c33-43d0-a9f2-c214cccc739d)

**Comment by siefkenj** [comment]
Can you try using only single words (no spaces) in between the `{{...}}`?

**Comment by 19hope44** [comment]
Snt this by email yesterday 2024 01 04 16:03
Have got the fields into the main email ok by creating the new message first then opening your extension and changing the settings to legacy instead of your default Nanjucks. They work using the correct field names as per the *csv file.
What I cannot do is add the recipient email. I assumed that this is accessed from the same *csv file, but no. I also tried importing that file into my address book (as a separate address book, not integrated into the standard address book). I have tried using the field names from the TB address book, as given and without spaces and with underlines. Nothing works!
Any ideas?

**Comment by siefkenj** [comment]
Try doing just `{{email}}` rather than `{{name}} <{{email}}>`

**Comment by 19hope44** [comment]
Sorry for the delay, had other MS issues (how surprising!)
Sadly that {{email}} doesn't work either. Nothing appears in the address field for the recipient. 
Am I correct that your mail merge extension takes the email address from the *.csv file? 
What else do you suggest I try?

**Comment by siefkenj** [comment]
Can you try copy-and-pasting your CSV into the spreadsheet instead of loading it as a file?

**Comment by 19hope44** [comment]
Sadly, again, no change. 
![Screen shot Mail Merge issue 2024 01 08 11-30](https://github.com/siefkenj/MailMergeP/assets/155631295/b2cd0c58-7026-4fe5-8e82-7b37b7e0922d)
When I enter the email field into the body of the email, it appears correctly (with its correct field name). Zilch in the address fields. Have tried both the correct email field name and {{email}}.
I have also tried putting another of my email addresses as a fixed email into the address field. It shows up ok. 
At a loss what to do next.

**Comment by siefkenj** [comment]
I have tested this, and the issue is that the subsitution keys between `{{ ... }}` must be single words with no spaces or special characters. Hope this helps!
