### ISSUE TITLE
save merged e-mails before sending?

### ISSUE THREAD

**Issue by rmmales** [siefkenj/MailMergeP#54]
This is a very nice and easy to use add-on.   I may have missed something - is it possible to direct the generated e-mails to the Outbox so that they can be further edited and personalized before sending?

TIA

**Comment by siefkenj** [comment]
Yes! If you do the "send later" option, they should be put in the drafts folder.

**Comment by rmmales** [comment]
Apologies,  I neglected to close out my question.  It works exactly as you
described, thank you very much.
